### ISSUE TITLE
Update clojure to 1.9.0

### ISSUE THREAD

**Issue by dannc** [Quantisan/docker-clojure#42]
Current images seem to be built with clojure 1.8.0.  Could we get that updated to 1.9.0?

**Comment by cap10morgan** [comment]
@dannc You probably knew this, but just in case (and for anyone else reading who wasn't aware): The version of Clojure we install in the image is just a convenience so you don't have to download it every time. You can still use any version of Clojure you want with these images.

However, I'll be pushing a commit to update the pre-installed version to 1.9.0 shortly. Thanks for flagging!

**Comment by cap10morgan** [comment]
Here's the [pull request](https://github.com/docker-library/official-images/pull/4028) to update the official images.

**Comment by D3nn** [comment]
Thanks @cap10morgan!  I was aware that the install of clojure in the image was as a convenience.  I was having issues still after updating the image myself to add clojure 1.9.0 but it turned out it was because my project was depending on a base project that still had a clojure 1.8.0.

Anyway, appreciate you creating an updated version and the PR to get it into dockerhub .
