### ISSUE TITLE
alpine based images shouldn't have rlwrap installed. 

### ISSUE THREAD

**Issue by DeLaGuardo** [Quantisan/docker-clojure#55]
rlwrap is not required for running Clojure and probably for alpine-based images nobody needs it. It suppose to be as small as possible.

**Comment by cap10morgan** [comment]
This used to be my position too, but it now is required to run the `clj` tool in the `tools-deps` variant. I wanted that to work out of the box, at least. So it seemed worth getting back in there. The `rlwrap` package itself is 320KB installed. I didn't dig into the size of any otherwise-unnecessary deps, though.

So I'm WONTFIX on this one, sorry. Or at the very least, I'd want to special case it so that it stays on the `tools-deps` variant.

But I will defer to what @Quantisan thinks we should do.

**Comment by DeLaGuardo** [comment]
Yes, for `clj`. But you can use `clojure` command without losing any functionality except better REPL experience. And I don't think that delivering "better REPL" is a primary goal for this image. That is my 2 cents for considering.

**Comment by DeLaGuardo** [comment]
There is also another argument https://github.com/Quantisan/docker-clojure/issues/52

**Comment by cap10morgan** [comment]
There are definitely arguments for and against on both sides here and reasonable people can and will disagree about either decision we make here. But when a 320KB installation with [minimal transitive dependencies](https://pkgs.alpinelinux.org/package/edge/testing/x86_64/rlwrap) makes a basic, documented component of one of these images work instead of throwing an error, I think that trade off is worth it.

**Comment by DeLaGuardo** [comment]
<img width="584" alt="image" src="https://user-images.githubusercontent.com/542042/44854619-50af2800-ac69-11e8-80ed-c5cde633241d.png">

To be clear - rlwrap with all dependencies requires 12MiB, not 320KB

**Comment by cap10morgan** [comment]
@Quantisan Thoughts on this one?

**Comment by Quantisan** [comment]
I agree that `rlwrap` is a nice to have but not essential. The question is where in the spectrum does it fall under. As @cap10morgan pointed out, there's a case for either to keep it or not.

- A case for:  In the [Clojure Getting Started page](https://clojure.org/guides/getting_started), it specifically called out to install `rlwrap`.
- A case against:  As @DeLaGuardo points out, it's an additional 8MB. `clojure:tools-deps-alpine` is 134MB. So that's almost 6% of space for a nice-to-have tool.

As @DeLaGuardo pointed out, the alpine ethos is about making images as small as possible. Seeing that it's 8MB, and not 320KB as we originally thought, then this isn't a trivial addition to the image. 

Given the above, I'm going to vote on removing `rlwrap`. @DeLaGuardo would you like to submit a PR for it?

**Comment by cap10morgan** [comment]
Just tried building tools-deps alpine images with and without rlwrap and the final size difference of the images as reported by `docker inspect` was 218KB saved by leaving rlwrap out. I think we're hyper-optimizing the wrong thing here.

But I've said my piece about the color of this particular bike shed.

I'm working on a branch that can build JDK 11 variants too without setting our hair on fire, so I've removed rlwrap from the alpine tools-deps variant in there.

**Comment by Quantisan** [comment]
Thanks @cap10morgan
