### ISSUE TITLE
Consider using the JVM Docker client

### ISSUE THREAD

**Issue by Quantisan** [Quantisan/docker-clojure#57]
Continuing this from #56 regarding https://github.com/lispyclouds/clj-docker-client

@lispyclouds what do you think a use case would be? The obvious is that we can avoid calling shell commands to build the images. What benefit would that provide?

**Comment by lispyclouds** [comment]
For me using Docker's REST API via the JVM client over generating custom shell commands has some of the following benefits:

- Less error prone. Generating shell commands and parsing the output increases the likelihood of us getting errors in the even of the format changes. Also this involves parsing of unstructured output which is also a source of errors. Using the JVM client you would get a consistent API with response as Clojure data structures. Having a good suite of unit tests in my lib helps me with it.
- Easier connection management. Using the TCP connection its easier to connect to remote docker daemons, maintain an efficient connection pool, get better structured output and errors.
- Easier maintenance. As this wraps over a pretty well maintained java [client](https://github.com/spotify/docker-client) from Spotify, the responsibility of taking care of docker level changes is handled for us automatically. Hence our build system can be extended more easily.
- And for me, in the Clojure context this seems to be more idiomatic to reuse a well maintained java client than crafting custom bash commands which was the aim of using Clojure instead of bash in #56 

These are some of the use cases I can think of. Hope this helps 😄

**Comment by cap10morgan** [comment]
I see you have released https://github.com/lispyclouds/contajners @lispyclouds. Looks cool! I think that would be the library to prefer for this issue, yeah?

**Comment by lispyclouds** [comment]
Thanks a lot for considering it! Yes @cap10morgan contajners would be the recommended one now! Though its newer and less production ready unlike clj-docker-client, it much more optimized and flexible!

@Quantisan I can try to have a look for rasinig a PR, but trying hard to find time this week, would be great if someone else wants to take at it crack too! I can have a look as soon as I can!

Thanks again! 😄

**Comment by lispyclouds** [comment]
now that i see it, not much value in this given the current setup here. this should be closed. can reopen if i can think of a better way.
