### ISSUE TITLE
clojure missing ?

### ISSUE THREAD

**Issue by olymk2** [Quantisan/docker-clojure#74]
Running 

`docker run -it clojure:lein sh`

then trying to run clj or clojure results in clojure not found error, I can see in the docker file its building a fake project and installing clojure via that project, I guess this is not in the system path ?

This is also evident when i run lein uberjar I get the same error explaining clojure is not found.

am i missing something obvious here ?

**Comment by cap10morgan** [comment]
Those commands are found in the `tools-deps` variants of the image. With leiningen Clojure is handled more like a library. Try `lein repl` in those, for example.

**Comment by olymk2** [comment]
seems the reason for the error is related to lein plugins some of them expect a clojure executable,

https://github.com/RickMoynihan/lein-tools-deps/issues/79

This is similar to the issue I am observing and it would make sense the plugin I am using is using the clojure executable.

just replying hoping it will help others.

if you are using CI some commands like this will work.

- apt update
- apt install rlwrap
- curl -O https://download.clojure.org/install/linux-install-1.10.1.462.sh
- chmod +x linux-install-1.10.1.462.sh
- ./linux-install-1.10.1.462.sh

may also be other docker images with all the tools ready to go so that may be a better option / simpler options so you don't have this overhead.

**Comment by cap10morgan** [comment]
A `lein-tools-deps` plugin would indeed expect the tools-deps executables, since its purpose is to combine usage of the two. You could also start with a `tools-deps` variant and install leiningen in it if you wanted to.

If using tools-deps for dependencies and leiningen for other aspects of project management becomes a common Clojure usage scenario we may have to rethink our variants a little. But for now this is expected behavior.

**Comment by olymk2** [comment]
okay, I tend to use tool deps until i need the uberjar thats when i then need lein.

the inverse may be simpler I think lein is a one line install unlike installing clojure where you need rlwrap
