### ISSUE TITLE
Consider basing some images on `adoptopenjdk` instead of `openjdk`

### ISSUE THREAD

**Issue by xorgy** [Quantisan/docker-clojure#88]
The AdoptOpenJDK OpenJDK distribution gives me noticeably (30% ish) better performance out of the box with my Clojure application, and includes Shenandoah, which Oracle refuses to enable in the default build. In addition, AdoptOpenJDK has slim alpine images.

The one gap between them is, right now, the lack of an OpenJDK 15 distribution on AdoptOpenJDK, and some of the base distribution options are considered "unofficial".

**Comment by cap10morgan** [comment]
I think this situation has changed since this issue was opened. OpenJDK 17 has shenandoah, is the new LTS (and will soon be our default jdk version), AdoptOpenJDK is itself undergoing a big transition to the Eclipse Foundation w/ lots of renaming etc., and the debian slim variants have largely covered the alpine use cases.

I think given all of the above and the lack of other requests for this, I'm included to close this.

**Comment by xorgy** [comment]
Yeah, I think that in practice, when this matters, you'll be shipping an uberjar in the image, so you can use any base image you want.

**Comment by Quantisan** [comment]
we're now on Temurin (rebranded `adoptopenjdk`)
